server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usertable
    username: root
    password: Likhith
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  security:
#    user:
#      name: Likhith
#      password: 123456